language: node_js
node_js:
- 11.10.0
dist: trusty
sudo: required
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_70a1debe915f_key -iv $encrypted_70a1debe915f_iv -in gce.json.enc -out gce.json -d
- cd sg-angular  

install:
- npm install -g @angular/cli
- npm install @angular-devkit/build-angular  

before_script:
- cd ..
- npm link
- cd sg-angular
script:
- ng build

deploy:
  provider: gae
  project: swolegoals-233203
  keyfile: gce.json
  verbosity: debug
  on: master